stages:
  - deploy

deploy_production:
  stage: deploy
  script:
    - rsync -av * /var/www/wordle/wordle-front/ --no-perms --no-owner --no-group --omit-dir-times
    - cd /var/www/wordle/wordle-front/ && npm install && npm run build
    - pm2 restart wordle
  environment:
    name: production
    url: https://wordle.uz/
  only:
    - master
